#!/usr/bin/env bash

function print_help {
    echo 'Deploys the selbi-stripe-worker (aka the background service) for the specified stage.'
    echo 'Usage: ./deploy <stage>'
    echo '  * stage - The Selbi stage to deploy.'
    echo "            One of 'staging' or 'production'. You should not deploy to develop or your individual stage."
}

# Answer help request.
if [[ ( "$1" = "-h" ) || ( "$1" = "--help" ) || ( "$#" -ne 1 ) ]]
then
    print_help
    exit 0;
fi

stage=$1



if [[ "$stage" = "staging" ]]
then
    gcloud components update -q
    gcloud auth activate-service-account --key-file ../service-accounts/selbi-staging-service-account.json
    gcloud config set project selbi-staging

    cp selbiBuildResources/staging/app.yaml .
    cp ~/.npmrc .

    gcloud app deploy app.yaml -q

    rm .npmrc
    rm app.yaml
elif [[ "$stage" = "production" ]]
then
    gcloud components update -q
    gcloud auth activate-service-account --key-file ../service-accounts/selbi-production-service-account.json
    gcloud config set project selbi-production

    cp selbiBuildResources/production/app.yaml .
    cp ~/.npmrc .

    gcloud app deploy app.yaml -q

    rm .npmrc
    rm app.yaml
else
    echo "Did not recognize stage: $stage. Must be one of 'staging' or 'production'"
    exit 1
fi