const accountDeets =
{ id: 'acct_18hhfyJqbRpOQz1w',
  object: 'account',
  business_logo: null,
  business_name: null,
  business_url: null,
  charges_enabled: true,
  country: 'US',
  debit_negative_balances: false,
  decline_charge_on: { avs_failure: false, cvc_failure: false },
  default_currency: 'usd',
  details_submitted: false,
  display_name: null,
  email: null,
  external_accounts:
  { object: 'list',
    data: [],
    has_more: false,
    total_count: 0,
    url: '/v1/accounts/acct_18hhfyJqbRpOQz1w/external_accounts' },
  keys:
  { secret: 'sk_test_DrPXia6m3jt50KEcBU9Hwxr9',
    publishable: 'pk_test_6Dls621ZON7TUa7oljHzx4xj' },
  legal_entity:
  { address:
  { city: 'San Francisco',
    country: 'US',
    line1: '655 Natoma Street',
    line2: 'Apt C',
    postal_code: '94103',
    state: 'CA' },
    business_name: null,
    business_tax_id_provided: false,
    dob: { day: 20, month: 3, year: 1990 },
    first_name: 'Matt',
    last_name: 'Dailey',
    personal_id_number_provided: false,
    ssn_last_4_provided: true,
    type: 'individual',
    verification:
    { details: null,
      details_code: null,
      document: null,
      status: 'unverified' } },
  managed: true,
  metadata: {},
  product_description: null,
  statement_descriptor: null,
  support_email: null,
  support_phone: null,
  timezone: 'Etc/UTC',
  tos_acceptance:
  { date: 1471016065,
    ip: '2601:645:8004:1b30:f17f:485a:a74c:1cba',
    user_agent: null },
  transfer_schedule: { delay_days: 2, interval: 'daily' },
  transfers_enabled: false,
  verification:
  { disabled_reason: null,
    due_by: null,
    fields_needed: [ 'external_account', 'legal_entity.personal_id_number' ] } }

const bankToken = { id: 'btok_8zi7nwIPjczbYk',
  object: 'token',
  bank_account:
  { id: 'ba_18hihQLzdXFwKk7fSpjRi2LJ',
    object: 'bank_account',
    account_holder_name: '\'Matt Dailey\'',
    account_holder_type: 'individual',
    bank_name: 'STRIPE TEST BANK',
    country: 'US',
    currency: 'usd',
    last4: '6789',
    routing_number: '110000000',
    status: 'new',
    name: '\'Matt Dailey\'' },
  client_ip: '67.169.95.125',
  created: 1471020000,
  livemode: false,
  type: 'bank_account',
  used: false };

const piiToken = { id: 'pii_18hipLLzdXFwKk7f9BjtVwqV',
  object: 'token',
  client_ip: '67.169.95.125',
  created: 1471020491,
  livemode: false,
  type: 'pii',
  used: false }
