# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.106.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :staging do
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Selbi Staging", use_legacy_build_api: true)
    testflight

    slack(message: "Successfully uploaded a new Staging build for test flight.")
  end

  desc "Deploy a new version to the App Store"
  lane :production do
    # increment last digit of version number to mark this as a release.
    increment_version_number

    match(type: "appstore")
    gym(scheme: "Selbi Production", use_legacy_build_api: true)
    testflight

    slack(message: "Successfully uploaded a new Production build for test flight.")
  end

  desc "Mark this version as a production release"
  lane :mark_production do
    # increment last digit of version number to mark this as a release.
    increment_version_number
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
