# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Selbi' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Selbi
  pod 'FirebaseAnalytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'

  target 'SelbiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
